app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
